// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentFile(arg1) {
  return window['go']['api']['VMPEngine']['AddRecentFile'](arg1);
}

export function AnalyzeELF(arg1) {
  return window['go']['api']['VMPEngine']['AnalyzeELF'](arg1);
}

export function GetDataDir() {
  return window['go']['api']['VMPEngine']['GetDataDir']();
}

export function GetRecentFiles() {
  return window['go']['api']['VMPEngine']['GetRecentFiles']();
}

export function Protect(arg1) {
  return window['go']['api']['VMPEngine']['Protect'](arg1);
}

export function SelectFile() {
  return window['go']['api']['VMPEngine']['SelectFile']();
}

export function SelectSaveFile(arg1) {
  return window['go']['api']['VMPEngine']['SelectSaveFile'](arg1);
}

export function Startup(arg1) {
  return window['go']['api']['VMPEngine']['Startup'](arg1);
}
