// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function AddRecentFile(arg1:string):Promise<void>;

export function AnalyzeELF(arg1:string):Promise<Record<string, any>>;

export function GetDataDir():Promise<string>;

export function GetRecentFiles():Promise<Array<Record<string, string>>>;

export function Protect(arg1:Record<string, any>):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectSaveFile(arg1:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
